name: Build Android APK
on:
  push:
    branches:
      - master # تأكد أن هذا هو اسم الفرع الرئيسي لديك (master أو main)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: |
          npm install
          # إجبار النظام على تثبيت المكتبات الناقصة وتصحيح التوافق مع SDK 52
          npx expo install expo-asset expo-constants --fix

      - name: 🚀 Build APK with EAS
        run: npx eas build --platform android --profile preview --non-interactive
